export enum CoordinatorState {
  INIT = 'INIT',
  VOTING = 'VOTING',
  COMMITTING = 'COMMITTING',
  COMMITTED = 'COMMITTED',
  ABORTING = 'ABORTING',
  ABORTED = 'ABORTED',
}

export enum TransactionType {
  MATERIAL_TRANSFER = 'MATERIAL_TRANSFER',
}

export enum ResourceType {
  MATERIAL = 'material',
  PRODUCT = 'product',
}

export enum VoteValue {
  YES = 'YES',
  NO = 'NO',
}

export enum LogEvent {
  TRANSACTION_CREATED = 'TRANSACTION_CREATED',
  VOTE_REQUEST_SENT = 'VOTE_REQUEST_SENT',
  PARTICIPANT_VOTED_YES = 'PARTICIPANT_VOTED_YES',
  PARTICIPANT_VOTED_NO = 'PARTICIPANT_VOTED_NO',
  ALL_VOTES_RECEIVED = 'ALL_VOTES_RECEIVED',
  DECISION_COMMIT = 'DECISION_COMMIT',
  DECISION_ABORT = 'DECISION_ABORT',
  COMMIT_ACK_RECEIVED = 'COMMIT_ACK_RECEIVED',
  ABORT_ACK_RECEIVED = 'ABORT_ACK_RECEIVED',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
  RECOVERY_INITIATED = 'RECOVERY_INITIATED',
}

export enum AbortReason {
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  PARTICIPANT_TIMEOUT = 'PARTICIPANT_TIMEOUT',
  PARTICIPANT_REJECTED = 'PARTICIPANT_REJECTED',
  UNKNOWN = 'UNKNOWN',
}
